"""Create initial schema

Revision ID: 45aa84cd7a8d
Revises: bfbd24d1cd9f
Create Date: 2025-09-23 11:15:48.284890

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '45aa84cd7a8d'
down_revision: Union[str, Sequence[str], None] = 'bfbd24d1cd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
