"""Create initial schema

Revision ID: ac225d26711f
Revises: ef3076b4f05e
Create Date: 2025-10-06 14:04:21.501831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac225d26711f'
down_revision: Union[str, Sequence[str], None] = 'ef3076b4f05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_product_product_id_fkey'), 'order_product', type_='foreignkey')
    op.create_foreign_key(None, 'order_product', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('product_category_product_id_fkey'), 'product_category', type_='foreignkey')
    op.create_foreign_key(None, 'product_category', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_category', type_='foreignkey')
    op.create_foreign_key(op.f('product_category_product_id_fkey'), 'product_category', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.create_foreign_key(op.f('order_product_product_id_fkey'), 'order_product', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
